# Generated by Django 4.0.2 on 2022-02-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autentications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaluser',
            old_name='emploerNo',
            new_name='id',
        ),
    ]
